services:
  postgres:
    image: postgres:15
    container_name: warehouse_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-warehouse_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-warehouse_password}
      POSTGRES_DB: ${POSTGRES_DB:-warehouse_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - warehouse_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warehouse_user -d warehouse_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  warehouse_network:
    driver: bridge